import type { Metadata } from "next";
import Navbar from "@/components/navbar"
import "./globals.css";

export const metadata: Metadata = {
  title: "Gabe's Milestone 2",
  description: "Generated by Gabe",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
